FirstBranch
DenisZadorozhniy/StreamSerenity pull request #1
Opened 2022-03-16 18:36 UTC by DenisZadorozhniy

2022-03-17 11:17 UTC, antonborzyh requested changes
Форматирование в файлах (проверить пробелы).
Отсутствует пустая строка в конце файлов.

2022-03-17 11:17 UTC, antonborzyh commented on pom.xml
> +</project>
java просит о пустой строке в конце файла. Валидно для всех файлов в ПР.

2022-03-17 11:17 UTC, antonborzyh commented on src/main/java/pages/ActionPage.java
> +    @FindBy(xpath = "//div[contains(@id,'tab_select_TopSellers')]")
```suggestion
    @FindBy(id = "tab_select_TopSellers")
```

2022-03-17 11:17 UTC, antonborzyh commented on src/main/java/pages/ActionPage.java
> +    private List<WebElement>priceGames;
" //div[contains(@id,'TopSellersTable')]//div[contains(@class,'discount_pct')] " - дублируется. Можно вынести в константу.

2022-03-17 11:17 UTC, antonborzyh commented on src/main/java/pages/ActionPage.java
> +        element(topSellersBtn).click();
для чего выполняется вызов element(topSellersBtn) ?

2022-03-17 11:17 UTC, antonborzyh commented on src/test/java/TestSteps.java
> +public class TestSteps extends UIInteractions {
Шаги следует разбить. Либо по смысловому признаку, либо к привязке к Page Object.

2022-03-17 11:17 UTC, antonborzyh commented on src/test/java/TestSteps.java
> +        mainStreamPage.open();
Лучше вынести в отдельный метод, т.к. по идее каждый UI тест будет начинаться с вызова этого метода.

2022-03-17 11:17 UTC, antonborzyh commented on src/test/java/TestSteps.java
> +        Assert.assertTrue("Value is not the same",checkPriceAndDiscount);
Ассерт не информативен. Если тест упадет, будет непонятно по какой причине.
Ассерт для boolean следует использовать, когда, например, проверяется элемент на какое-либо состояние.
В данном случае происходит сравнение значений, и в ассерт должны передаваться эти значения. Ожид и Факт.

2022-03-17 11:17 UTC, antonborzyh commented on src/test/java/TestSteps.java
> +        downloadSteamPage.deleteSteam();
вызов downloadSteamPage.deleteSteam() не произойдет, если ассерт упадет. Удаление следует вынести в After метод.

2022-03-17 11:17 UTC, antonborzyh commented on src/main/java/pages/DownloadSteamPage.java
> +    }
Метод deleteSteam() не имеет отношения к DownloadSteamPage.

2022-03-17 11:17 UTC, antonborzyh commented on src/main/java/pages/DownloadSteamPage.java
> +    private WebElement downloadSteamBtn;
Элемент downloadSteamBtn доступен с любой вебстраницы приложения. Не вижу необходимость создавать отдельный PO для этого.

2022-03-17 11:17 UTC, antonborzyh commented on src/main/java/pages/DownloadSteamPage.java
> +    }
метод выполняет сразу три функции:
1. получение href
2. скачивание
3. проверка

Надо разбить.

2022-03-17 11:17 UTC, antonborzyh commented on src/main/java/utils/FileUtils.java
> +    public static boolean checkFileУExists(String path){
checkFileУExists - опечатка?

2022-03-17 11:17 UTC, antonborzyh commented on src/main/java/utils/LoadFromProperties.java
> +        }
Для перехваченных exception выполняется одно и то же действие.
Т.к. FileNotFoundException наследует IOException, можно оставить только последний.

2022-03-17 11:17 UTC, antonborzyh commented on src/main/java/utils/ScriptUtils.java
> +    public static JavascriptExecutor js = (JavascriptExecutor) driver;
В serenity уже реализован JavascriptExecutorFacade. Нет смысла работать с Selenium.

2022-03-17 12:58 UTC, DenisZadorozhniy commented on src/main/java/pages/DownloadSteamPage.java
> +    private WebElement downloadSteamBtn;
Так это же не простая зеленая кнопка которая доступна с любого места сайта, это кнопка скачать Стим которая лежит на отдельной странице.

2022-03-17 13:07 UTC, DenisZadorozhniy commented on src/main/java/utils/FileUtils.java
> +    public static boolean checkFileУExists(String path){
Да)

2022-03-17 13:09 UTC, antonborzyh commented on src/main/java/pages/DownloadSteamPage.java
> +    private WebElement downloadSteamBtn;
Да. Согласен. PO нужен в данном случае. Но в классе должны быть только элемент кнопка и метод клика по ней или получения значения атрибута.
Методы работы с файлом должны быть в соответствующем классе.

2022-03-17 14:28 UTC, antonborzyh requested changes

2022-03-17 14:28 UTC, antonborzyh commented on src/main/java/pages/DownloadSteamPage.java
> +    }
Надо вынести в FileUtils. Эти методы не имеют отношения к PO.

2022-03-17 14:28 UTC, antonborzyh commented on src/main/java/pages/ActionPage.java
> +    private final String path = "//div[contains(@id,'TopSellersTable')]//div[contains(@Class,'discount_pct')] ";
Это уже константа. Обозначается в стиле SMTH_CONSTANT.
И path в данном случае не передает смысловое значение константы. Надо поконкретнее описать.

2022-03-17 14:28 UTC, antonborzyh commented on src/main/java/utils/FileUtils.java
> +    public static boolean checkFileExists(String path) {
Метод, возвращающей boolean, принято называть isSmth().

2022-03-17 14:28 UTC, antonborzyh commented on src/test/java/BaseTest.java
> +    }
Думаю, этот After должен быть использован только для конкретного теста. В данном случае он будет вызываться у всех тестов, класс которых будет наследовать BaseTest.

2022-03-17 15:54 UTC, antonborzyh requested changes

2022-03-17 15:54 UTC, antonborzyh commented on src/main/java/pages/ActionPage.java
> +    @FindBy(xpath = "" + DISCOUNT_PATH + "//..//..//div[contains(@class,'tab_item_name')]")
```suggestion
    @FindBy(xpath = DISCOUNT_PATH + "//..//..//div[contains(@class,'tab_item_name')]")
```

2022-03-17 15:54 UTC, antonborzyh commented on src/main/java/pages/ActionPage.java
> +    @FindBy(xpath = "" + DISCOUNT_PATH + "")
```suggestion
    @FindBy(xpath = DISCOUNT_PATH)
```

2022-03-17 15:54 UTC, antonborzyh commented on src/main/java/pages/ActionPage.java
> +    @FindBy(xpath = "" + DISCOUNT_PATH + "//..//..//div[contains(@class,'discount_final_price')]")
```suggestion
    @FindBy(xpath = DISCOUNT_PATH + "//..//..//div[contains(@class,'discount_final_price')]")
```

2022-03-18 10:31 UTC, antonborzyh requested changes

2022-03-18 10:31 UTC, antonborzyh commented on src/main/java/utils/StringUtils.java
> +    }
метод не используется

2022-03-18 10:31 UTC, antonborzyh commented on src/main/java/utils/StringUtils.java
> +    }
зачем обертка над String.replace ?

2022-03-18 10:31 UTC, antonborzyh commented on src/main/java/utils/StringUtils.java
> +    public static String getOnlyNumbers(String str) {
Можно просто добавить в параметр - строку regexp и сделать метод более универсальным.

2022-03-18 10:31 UTC, antonborzyh commented on src/main/java/utils/StringUtils.java
> +        Matcher matcher = Pattern.compile("\\d{0,4}").matcher(str);
РВ - некорректно работает.

2022-03-18 10:31 UTC, antonborzyh commented on src/main/java/utils/StringUtils.java
> +        return matcher.group();
Игнорируется результат выполнения find().
Если не будет найдено соответствие group() выбросит java.lang.IllegalStateException: No match found и тест упадет.

2022-03-21 08:46 UTC, antonborzyh requested changes

2022-03-21 08:46 UTC, antonborzyh commented on src/main/java/pages/ValidationPage.java
> +    public Boolean IsDisplayValidationPage() {
Название метода начинается в нижнем регистре.

2022-03-21 08:46 UTC, antonborzyh commented on src/main/java/pages/ValidationPage.java
> +    private WebElement ageBtn;
У WebElementFacade в serenity реализованы методы для работы с select.

2022-03-22 12:30 UTC, antonborzyh requested changes

2022-03-22 12:30 UTC, antonborzyh commented on src/test/java/TestSteps.java
> +        Assert.assertEquals(price, ConversionUtils.conversionToDoubleValue(priceGame,"\\d{1,4}"));
Значение полученное из ConversionUtils.conversionToDoubleValue(priceGame,"\\d{1,4}")  лучше вынести в отдельную переменную. Так будет проще читать код.

2022-03-22 12:30 UTC, antonborzyh commented on src/test/java/TestSteps.java
> +        Assert.assertEquals(discount, discountGame);
discountGame - может быть не инициализирован.
Посмотри про session variable в Serenity.

2022-03-22 12:30 UTC, antonborzyh commented on src/main/java/utils/FileUtils.java
> +    }
А в чем смысл этой метода-обертки saveFile()?

2022-03-22 12:30 UTC, antonborzyh commented on src/main/java/utils/FileUtils.java
> +    }
Аналогичный вопрос, как и с saveFile()?

2022-03-22 12:30 UTC, antonborzyh commented on src/main/java/utils/ConversionUtils.java
> +    }
Метод, судя по названию, должен просто конвертировать строку в double.
Но он принимает при этом regexp, который по идее к конвертации отношения не имеет.
На мой субъективный взгляд данный метод избыточен. В коде можно вызывать StringUtils.getOnlyNumbers(msg,regex) и на ходу переводить полученное значение в необходимый тебе тип данных (Integer, Double, Long и т.п.).

2022-03-22 12:30 UTC, antonborzyh commented on src/main/java/utils/StringUtils.java
> +    }
Т.к. метод теперь принимает regexp, его название не передает смысл его работы.
Парсить можно как числа, так и другие символы (в зависимости от regexp).

2022-03-22 12:30 UTC, antonborzyh commented on src/main/java/pages/ValidationPage.java
> +    private WebElementFacade ageOption;
Т.к. "WebElementFacade ageBtn" имеет локатор селекта, у него можно вызывать метод selectBy...(smth). Т.е. работать с options селекта (подсказка - ageOption не нужен).

2022-03-22 12:38 UTC, antonborzyh requested changes

2022-03-22 12:38 UTC, antonborzyh commented on src/main/java/pages/ActionPage.java
> +    public String getMostDiscounts() {
здесь возвращается одно значение. Корректнее было бы назвать getMaxDiscount() ?

2022-03-22 12:38 UTC, antonborzyh commented on src/main/java/pages/MainStreamPage.java
> +    }
Данный набор элементов и метод можно вынести в отдельный класс для работы с Меню и сделать возможным передавать в метод значения, которые нужно в меню кликнуть.
Т.е. реализовать класс как отдельный компонент на странице, содержащий в себе поля-элементы и универсальный метод, принимающий название меню и подменю и выполняющий клики.

2022-03-25 15:50 UTC, merged

2022-03-31 12:28 UTC, antonborzyh commented on src/test/java/TestSteps.java
> +        Assert.assertEquals(price, ConversionUtils.conversionToDoubleValue(priceGame,"\\d{1,4}"));
Здесь речь шла про значение которое возвращает " ConversionUtils.conversionToDoubleValue(priceGame,"\d{1,4}") ".